Question 1: Compare and contrast NLTK and spaCy in terms of features, ease of use,
and performance.
- frectures
  - NLTK
    - Tokenization, stemming, lemmatization
    - Corpora and lexical resources (e.g., WordNet)
    - Parsing (CFG/PCFG), classification, tagging
    - Educational utilities
    - Rich collection of sample datasets
    - Excellent for algorithm exploration and learning NLP concepts
  - spacy
    - Tokenization, POS tagging, dependency parsing
    - Named Entity Recognition (NER)
    - Lemmatization
    - Vector embeddings
    - Supports custom pipelines
    - Built-in pre-trained statistical and transformer models
- Ease of Use
  - NLTK
    - Steeper learning curve initially
    - Requires more manual setup (e.g., downloading corpora)
    - API style can be repetitive and verbose
  - sapCy
    - Cleaner, high-level API
    - One-line model loading and processing
    - Pipeline runs end-to-end with minimal code
- Performance
  - NLTK
    - Component-based, often slower
    - Not optimized for speed
    - Uses pure Python implementations
  - spaCy
    - Highly optimized (Cython, efficient data structures)
    - Fast tokenization and parsing
    - Scales well for large datasets
    - Excellent for real-time NLP tasks

Question 2: What is TextBlob and how does it simplify common NLP tasks like
sentiment analysis and translation?
- TextBlob is a simple Python library built on top of NLTK and Pattern that provides an easy-to-use API for performing common Natural Language Processing (NLP) tasks.
- It is designed for beginners and developers who want to quickly implement NLP features without writing complex code.
- 1. Sentiment Analysis
   - sentiment analysis requires:
     - Data preprocessing
     - Training a classifier
     - Extracting polarity and subjectivity
   - TextBlob hides all this complexity.
   - It provides ready-made sentiment analysis
     - Polarity → whether text is positive, negative, or neutral
     - Subjectivity → whether text is personal opinion or fact
- 2. Translation
   - Text translation usually requires:
      - Connecting to a translation API
      - Writing authentication and network code
      - Handling language detection
    - It automatically:
      - Detects the language of the input text
      - Translates text into the target language
      - Uses online translation services behind the scenes

Question 3: Explain the role of Standford NLP in academic and industry NLP Projects
- The Stanford NLP Group is one of the world’s most influential research groups in Natural Language Processing (NLP).
It is part of Stanford University and is known for producing state-of-the-art NLP models, tools, and research papers.
- Their tools—like Stanford CoreNLP, Stanza, and the Stanford Parser—are widely used in research and real-world applications.
- Role in Academic NLP Projects
  - 1. Authoritative Research Contributions
    - Dependency parsing
    - Coreference resolution
    - Named entity recognition (NER)
    - Sentiment analysis
    - Machine translation
  - 2. Availability of High-quality Tools
    - They are academically trusted
    - They come with clear documentation
    - They support many languages
    - Text annotation
    - Linguistic analysis
  - 3. Reliable Annotation Standards
    - Treebanks
    - Annotated datasets
    - Evaluation benchmarks
- Role in Industry NLP Projects
  - 1. Production-grade NLP Pipelines
     - Tokenization
     - POS tagging
     - NER
     - Parsing
     - Sentiment analysis
  - 2. Multilingual Support
     - English
     - Chinese
     - Arabic
     - German
     - Spanish
  - 3. Proven Accuracy and Reliability
     - They are backed by strong research
     - They have consistently high accuracy
     - They are stable and well-tested

Question 4: Describe the architecture and functioning of a Recurrent Natural Network
(RNN).
- 1. Architecture of an RNN
   - 1. Input Layer
     - Takes sequential data one element at a time (e.g., word by word or time-step by time-step).
   - 2. Hidden Layer (Core of RNN)
     - Contains neurons with recurrent connections, meaning each neuron receives:
     - The current input Xt
     - The previous hidden state ht-1
     - This allows RNNs to maintain memory of past inputs.
    - 3. Output Layer
      - Produces output at each time-step or only at the final time-step, depending on the task.
      - Example: language modeling → output at every step
      - Sentiment analysis → output only at the end
    - 4. Shared Weights
      - RNN uses the same set of weights at every time-step.
      - This makes it efficient and suitable for variable-length sequences.
- 2. Functioning of an RNN
    - Step 1: Receive Input
      - At time-step t, the network receives an input
    - Step 2: Update Hidden State
    - Step 3: Generate Output
    - Step 4: Repeat for All Time Steps



Question 5: What is the key difference between LSTM and GRU networks in NLP
applications?
- LSTM has 3 gates and a separate memory cell.
  - Forget gate
  - Input gate
  - Output gate
  - Cell state (long-term memory)
  - This makes LSTMs more powerful but more complex and computationally heavier.
- GRU has only 2 gates and no separate memory cell.
  - Update gate
  - Reset gate
    - It combines the cell state and hidden state, making GRUs simpler, faster, and often performing equally well with fewer parameters.

Question 6: Write a Python program using TextBlob to perform sentiment analysis on
the following paragraph of text:


In [1]:
from textblob import TextBlob

text = """I had a great experience using the new mobile banking app.
The interface is intuitive, and customer support was quick to resolve my issue.
However, the app did crash once during a transaction, which was frustrating."""

# Create TextBlob object
blob = TextBlob(text)

# Perform sentiment analysis
sentiment = blob.sentiment

print("Polarity:", sentiment.polarity)
print("Subjectivity:", sentiment.subjectivity)

Polarity: 0.21742424242424244
Subjectivity: 0.6511363636363636


Question 7: Given the sample paragraph below, perform string tokenization and
frequency distribution using Python and NLTK:

In [3]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

text = """Natural Language Processing (NLP) is a fascinating field that combines
linguistics, computer science, and artificial intelligence. It enables machines to
understand, interpret, and generate human language. Applications of NLP include
chatbots, sentiment analysis, and machine translation. As technology advances,
the role of NLP in modern solutions is becoming increasingly critical."""

# Download required tokenizers
nltk.download('punkt')
nltk.download('punkt_tab')

# Tokenization
tokens = word_tokenize(text)
print("Tokens:")
print(tokens)

# Frequency Distribution
freq_dist = FreqDist(tokens)

print("\nFrequency Distribution:")
for word, freq in freq_dist.items():
    print(word, ":", freq)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Tokens:
['Natural', 'Language', 'Processing', '(', 'NLP', ')', 'is', 'a', 'fascinating', 'field', 'that', 'combines', 'linguistics', ',', 'computer', 'science', ',', 'and', 'artificial', 'intelligence', '.', 'It', 'enables', 'machines', 'to', 'understand', ',', 'interpret', ',', 'and', 'generate', 'human', 'language', '.', 'Applications', 'of', 'NLP', 'include', 'chatbots', ',', 'sentiment', 'analysis', ',', 'and', 'machine', 'translation', '.', 'As', 'technology', 'advances', ',', 'the', 'role', 'of', 'NLP', 'in', 'modern', 'solutions', 'is', 'becoming', 'increasingly', 'critical', '.']

Frequency Distribution:
Natural : 1
Language : 1
Processing : 1
( : 1
NLP : 3
) : 1
is : 2
a : 1
fascinating : 1
field : 1
that : 1
combines : 1
linguistics : 1
, : 7
computer : 1
science : 1
and : 3
artificial : 1
intelligence : 1
. : 4
It : 1
enables : 1
machines : 1
to : 1
understand : 1
interpret : 1
generate : 1
human : 1
language : 1
Applications : 1
of : 2
include : 1
chatbots : 1
sentiment : 1

Question 8: Implement a basic LSTM model in Keras for a text classification task using
the following dummy dataset. Your model should classify sentences as either positive
(1) or negative (0).

In [4]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Dataset
texts = [
    "I love this project",          # Positive
    "This is an amazing experience",# Positive
    "I hate waiting in line",       # Negative
    "This is the worst service",    # Negative
    "Absolutely fantastic!"         # Positive
]

labels = [1, 1, 0, 0, 1]

# -------------------------------
# 1. Tokenization
# -------------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

vocab_size = len(tokenizer.word_index) + 1
sequences = tokenizer.texts_to_sequences(texts)

print("Word Index:", tokenizer.word_index)
print("Sequences:", sequences)

# -------------------------------
# 2. Padding
# -------------------------------
max_len = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

print("\nPadded Sequences:")
print(padded_sequences)

# -------------------------------
# 3. Build LSTM Model
# -------------------------------
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=max_len))
model.add(LSTM(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# -------------------------------
# 4. Train the Model
# -------------------------------
labels = np.array(labels)
model.fit(padded_sequences, labels, epochs=10, verbose=1)

# -------------------------------
# 5. Test on a new sample
# -------------------------------
test_text = ["This project is fantastic"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq, maxlen=max_len, padding='post')

prediction = model.predict(test_pad)
print("\nPrediction:", prediction)

Word Index: {'this': 1, 'i': 2, 'is': 3, 'love': 4, 'project': 5, 'an': 6, 'amazing': 7, 'experience': 8, 'hate': 9, 'waiting': 10, 'in': 11, 'line': 12, 'the': 13, 'worst': 14, 'service': 15, 'absolutely': 16, 'fantastic': 17}
Sequences: [[2, 4, 1, 5], [1, 3, 6, 7, 8], [2, 9, 10, 11, 12], [1, 3, 13, 14, 15], [16, 17]]

Padded Sequences:
[[ 2  4  1  5  0]
 [ 1  3  6  7  8]
 [ 2  9 10 11 12]
 [ 1  3 13 14 15]
 [16 17  0  0  0]]
Epoch 1/10


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.8000 - loss: 0.6892
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.8000 - loss: 0.6867
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8000 - loss: 0.6841
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.6000 - loss: 0.6814
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.6000 - loss: 0.6786
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6756
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 0.6725
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6000 - loss: 0.6692
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.6000 - loss: 0.6657
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6000 - loss: 0.6619
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step

Prediction: [[0.53088975]]


Question 9: Using spaCy, build a simple NLP pipeline that includes tokenization,
lemmatization, and entity recognition. Use the following paragraph as your dataset:

In [6]:
import spacy

# Load spaCy English model
nlp = spacy.load("en_core_web_sm")

text = """Homi Jehangir Bhaba was an Indian nuclear physicist who played a key role
in the development of India’s atomic energy program. He was the founding director
of the Tata Institute of Fundamental Research (TIFR) and was instrumental in
establishing the Atomic Energy Commission of India."""

# Process text
doc = nlp(text)

# -------------------------------
# 1. Tokens and Lemmas
# -------------------------------
print("Tokens and Lemmas:")
for token in doc:
    print(token.text, " → ", token.lemma_)

# -------------------------------
# 2. Named Entities (Correct Loop)
# -------------------------------
print("\nNamed Entities:")
for ent in doc.ents:
    print(ent.text, " → ", ent.label_)

Tokens and Lemmas:
Homi  →  Homi
Jehangir  →  Jehangir
Bhaba  →  Bhaba
was  →  be
an  →  an
Indian  →  indian
nuclear  →  nuclear
physicist  →  physicist
who  →  who
played  →  play
a  →  a
key  →  key
role  →  role

  →  

in  →  in
the  →  the
development  →  development
of  →  of
India  →  India
’s  →  ’s
atomic  →  atomic
energy  →  energy
program  →  program
.  →  .
He  →  he
was  →  be
the  →  the
founding  →  found
director  →  director

  →  

of  →  of
the  →  the
Tata  →  Tata
Institute  →  Institute
of  →  of
Fundamental  →  Fundamental
Research  →  Research
(  →  (
TIFR  →  TIFR
)  →  )
and  →  and
was  →  be
instrumental  →  instrumental
in  →  in

  →  

establishing  →  establish
the  →  the
Atomic  →  Atomic
Energy  →  Energy
Commission  →  Commission
of  →  of
India  →  India
.  →  .

Named Entities:
Homi Jehangir Bhaba  →  FAC
Indian  →  NORP
India  →  GPE
the Tata Institute of Fundamental Research  →  ORG
the Atomic Energy Commission of India  →  ORG


Question 10: You are working on a chatbot for a mental health platform. Explain how
you would leverage LSTM or GRU networks along with libraries like spaCy or Stanford
NLP to understand and respond to user input effectively. Detail your architecture, data
preprocessing pipeline, and any ethical considerations.


In [7]:
# -------------------------------------------
# 1. Import Libraries
# -------------------------------------------
import spacy
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, GRU, Dense

# Load spaCy for preprocessing
nlp = spacy.load("en_core_web_sm")

# -------------------------------------------
# 2. Sample Mental-Health User Inputs (Dummy Data)
# -------------------------------------------
texts = [
    "I feel very anxious today",
    "I'm really happy with my progress",
    "I am stressed and tired",
    "I feel like giving up",
    "Today was a peaceful day"
]

# Labels for emotion classification (dummy)
# 0 = negative emotion, 1 = positive emotion
labels = [0, 1, 0, 0, 1]

# -------------------------------------------
# 3. spaCy Preprocessing Function
# -------------------------------------------
def preprocess_text(text):
    doc = nlp(text)
    lemmas = [token.lemma_.lower() for token in doc if not token.is_stop]
    return " ".join(lemmas)

processed_texts = [preprocess_text(t) for t in texts]
print("Processed Texts:", processed_texts)

# -------------------------------------------
# 4. Tokenization + Padding
# -------------------------------------------
tokenizer = Tokenizer()
tokenizer.fit_on_texts(processed_texts)

vocab_size = len(tokenizer.word_index) + 1

sequences = tokenizer.texts_to_sequences(processed_texts)
max_len = max(len(seq) for seq in sequences)

padded = pad_sequences(sequences, maxlen=max_len, padding='post')
labels = np.array(labels)

# -------------------------------------------
# 5. Build LSTM/GRU Model
# -------------------------------------------
model = Sequential()
model.add(Embedding(vocab_size, 32, input_length=max_len))
model.add(GRU(32))        # Can replace GRU with LSTM(32)
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

print(model.summary())

# -------------------------------------------
# 6. Train Model
# -------------------------------------------
model.fit(padded, labels, epochs=10)

# -------------------------------------------
# 7. Test the Chatbot Pipeline
# -------------------------------------------
user_input = "I feel lonely and stressed"
clean_text = preprocess_text(user_input)
seq = tokenizer.texts_to_sequences([clean_text])
pad = pad_sequences(seq, maxlen=max_len, padding='post')

prediction = model.predict(pad)[0][0]

print("\nUser Input:", user_input)
print("Cleaned Input:", clean_text)
print("Model Prediction Score:", prediction)

if prediction > 0.5:
    print("Chatbot Response: I'm glad you're feeling positive today! I'm here to talk.")
else:
    print("Chatbot Response: I'm really sorry you're feeling this way. I'm here to listen.")

Processed Texts: ['feel anxious today', 'happy progress', 'stress tired', 'feel like give', 'today peaceful day']


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.4000 - loss: 0.6932
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.8000 - loss: 0.6897
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8000 - loss: 0.6862
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8000 - loss: 0.6827
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6000 - loss: 0.6791
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.6756
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.6719
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6682
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.6645
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6000 - loss: 0.6606
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 230ms/step

User Input: I feel lonely and stressed
Cleaned Input: feel lonely stress
Model Prediction Score: 0.46358326
Chatbot Response: 